pipeline {
    agent any

    stages {

        stage('Debug Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -R'
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('docker/backend') {
                    sh 'docker build -t backend-service:v1 .'
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('docker/frontend') {
                    sh 'docker build -t frontend-service:v1 .'
                }
            }
        }

        stage('Deploy Backend') {
            steps {
                sh 'kubectl apply -f k8s/backend-deployment.yaml'
                sh 'kubectl apply -f k8s/backend-service.yaml'
            }
        }

        stage('Deploy Frontend') {
            steps {
                sh 'kubectl apply -f k8s/frontend-deployment.yaml'
                sh 'kubectl apply -f k8s/frontend-service.yaml'
            }
        }

    }
}