pipeline {
    agent any

    stages {

        stage('Build Backend Image') {
            steps {
                sh '''
                cd docker/backend
                docker build -t backend-service:v1 .
                '''
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh '''
                cd docker/frontend
                docker build -t frontend-service:v1 .
                '''
            }
        }

        stage('Deploy Backend') {
            steps {
                sh 'kubectl apply -f k8s/backend-deployment.yaml'
                sh 'kubectl apply -f k8s/backend-service.yaml'
            }
        }

        stage('Deploy Frontend') {
            steps {
                sh 'kubectl apply -f k8s/frontend-deployment.yaml'
                sh 'kubectl apply -f k8s/frontend-service.yaml'
            }
        }

    }
}